### ISSUE TITLE
running ./CausaltTrail in batch mode

### ISSUE THREAD

**Issue by kingfish777** [dstoeckel/causaltrail#1]
Greetings: Is it possible to run ./CausalTrail in batch mode? I'd like to be able to calculate estimates of counterfactual interventions in batch mode with my (pharmacovigilance) data. I attempted to do this, but all that I get is a console error: That is, to clarify, I would like to be able to run batch queries from the command line (without the GUI and without direct human intervention).  
Thanks!
Kingfish777 (Scott Malec)

---
./CausalTrail test/data/StudentData.txt ./student_batch.txt test/data/controlStudent.json test/data/Student.sif test/data/Student.na
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Unsupported file type
Aborted (core dumped)
---

where student_batch.txt looks like this: 
---
student_batch.txt ? Difficulty = d1
? Difficulty = d1 ! do SAT = s0
? Difficulty = d1 Letter = l0 ! do SAT = s0
? Difficulty = d1 Letter = l0 Intelligence = i0 ! do SAT = s0
? Difficulty = d1 Letter = l0 ! do SAT = s0
---

**Comment by Florian411** [comment]
Thanks for your interest in CausalTrail. 
Unfortunately, it is not possible to run batch queries from the command line. This is supported by the GUI only.

**Comment by kingfish777** [comment]
Don't you think that this is a valid use-case for your software?

**Comment by Florian411** [comment]
It is of course interesting, but as it is already implemented in the gui, it is not on the top priority list to add this also in the console version.

**Comment by kingfish777** [comment]
I understand having a priority list. Would you mind if I went ahead and added that capability to the console in a new branch?

**Comment by Florian411** [comment]
Feel free to do so.
